
api:
  version: "v1"

http:
  listener:
    path: "american-flights-sa/api/${api.version}"
    timeout: "120000" #2 min

db:
  mysql:
    host: "mudb.mule-training.com"
    port: "3306"
    user: "![80NWtBpoQzs=]"
    password: "![80NWtBpoQzs=]"
    database: "training"