#%RAML 1.0 Library

types:
  
  AmericanFlight:
    properties:
      ID?:
        type: integer
        required: false
        displayName: ID
        description: The unique identefier of the flight
        example: 1
      code:
        type: string
        displayName: Flight code
        description: Combined code1 and code2 for flight indentefication
        example: "ER38sd"
      price:
        type: number
        format: float
        displayName: Price
        description: Ticket cost for the flight
        example: 400.00
      departureDate:
        type: string
        displayName: Departure Date
        description: Scheduled date of departure
        example: "2025/03/15"
      origin:
        type: string
        displayName: Origin
        description: Code of the origin airport
        example: "CLE"
      destination:
        type: string
        displayName: Destination
        description: Code of the destination airport
        example: "SFO"
      emptySeats:
        type: integer
        displayName: Empty Seats
        description: Number of seats available for booking
        example: 0
      plane:
        type: object
        required: false
        displayName: Plane
        description: Information about the airplane
        properties:
          type:
            type: string
            displayName: Type
            description: Model type of the airplane
            example: "Boeing 737"
          totalSeats:
            type: integer
            displayName: Total Seats
            description: Total number of seats in the airplane
            example: 150