#%RAML 1.0

title: American Flights System API
version: v1

uses:
  american-flight: datatypes/american-flight.raml

#===============================================================
# Libraries
#===============================================================

/flights:
  get:
    queryParameters:
      destination:
        required: false
        enum:
          - SFO
          - LAX
          - CLE
    responses:
      200:
        body:
          application/json:
            type: american-flight.AmericanFlight[]
            example: !include examples/american-flights-response-200.json

  /{ID}:
    get:
      responses:
        200:
          body:
            application/json:
              type: american-flight.AmericanFlight
              example: !include examples/american-flight-response-200.json
    